### ISSUE TITLE
left align text in btn-block

### ISSUE THREAD

**Issue by misha-tgshv** [phonerefer/LinkTree#1]
Hi! Trying to edit layout, but not obtained this make yourself. How to do to  text in buttons was on the left? :)

<img width="1440" alt="screenshot_2020-06-21_22 46 31" src="https://user-images.githubusercontent.com/15308581/85228971-18b23f80-b411-11ea-89f6-edd0da1ad10f.png">

**Comment by irshad** [comment]
I don't understand what exactly you are saying?

**Comment by misha-tgshv** [comment]
as to make the text in left edge inside buttons? Replace the align center of the align left

**Comment by misha-tgshv** [comment]
sorry for bad English :)
